[package]
name = "quackrag-llm"
version.workspace = true
edition.workspace = true

[features]
default = ["candle"]
candle = [
    "dep:candle-core",
    "dep:candle-transformers",
    "dep:tokenizers",
    "dep:hf-hub",
]

[dependencies]
quackrag-core = { path = "../quackrag-core" }
candle-core = { version = "0.9", optional = true }
candle-transformers = { version = "0.9", optional = true }
tokenizers = { version = "0.21", optional = true }
hf-hub = { version = "0.4", optional = true }
async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true
futures.workspace = true
tokio = { workspace = true }
